from flask import Flask, render_template, request
import requests
import json

app = Flask(__name__)


# =========================================================
# OLLAMA AI FUNCTION
# =========================================================

def ask_ai(prompt):

    url = "http://localhost:11434/api/generate"

    data = {
        "model": "llama3.2:3b",
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.3,
            "num_predict": 250
        }
    }

    try:

        response = requests.post(
            url,
            json=data,
            timeout=120
        )

        if response.status_code == 200:

            result = response.json()

            return result["response"]

        else:

            return "AI Error: " + response.text

    except Exception as e:

        return "Could not connect to Ollama: " + str(e)


# =========================================================
# AGENT 1: AI STUDY PLANNER
# =========================================================

def study_planner_agent(subjects, hours, days):

    subjects = [
        s.strip()
        for s in subjects.split(",")
        if s.strip()
    ]

    try:
        hours = int(hours)
        days = int(days)

    except:

        return {
            "error": "Please enter valid numbers."
        }

    if not subjects:

        return {
            "error": "Please enter at least one subject."
        }

    prompt = f"""
You are an AI Study Planner Agent for a college student.

Create a practical study plan.

Subjects:
{", ".join(subjects)}

Study hours per day:
{hours}

Number of days:
{days}

Create a day-by-day study schedule.

For every day:
- Divide the available study time between the subjects.
- Give a specific topic or task to study.
- Include revision and practice where appropriate.

Rules:
- Use ONLY the subjects provided.
- Do not create more than {hours} study hours per day.
- Make the schedule realistic.
- Use simple English.
- Clearly separate each day.
- Do not give unnecessary explanations.

Format the answer like:

DAY 1

Hour 1 - Subject
Task

Hour 2 - Subject
Task

DAY 2

Hour 1 - Subject
Task

Continue until DAY {days}.
"""

    ai_response = ask_ai(prompt)

    return {
        "subjects": subjects,
        "hours": hours,
        "days": days,
        "ai_plan": ai_response
    }


# =========================================================
# AGENT 2: AI NOTES ANALYZER
# =========================================================

def notes_analyzer_agent(notes):

    if not notes.strip():

        return {
            "summary": [],
            "topics": [],
            "important_topics": [],
            "recommendation": "Please enter your study notes."
        }

    prompt = f"""
You are an AI Notes Analyzer Agent for a college student.

Analyze these study notes:

{notes}

Provide:

1. SUMMARY
Give exactly 3 short and clear points.

2. IMPORTANT TOPICS
Give exactly 5 important topics.

3. RECOMMENDATION
Give exactly 2 study recommendations.

Use simple English.

Do not use unnecessary explanations.
"""

    ai_response = ask_ai(prompt)

    return {

        "summary": [ai_response],

        "topics": [],

        "important_topics": [],

        "recommendation":
            "This analysis was generated by Llama 3.2 AI.",

        "original_notes": notes

    }


# =========================================================
# AGENT 3: AI QUIZ
# =========================================================

def quiz_agent(notes):

    if not notes.strip():
        return []

    prompt = f"""
Create exactly 5 multiple-choice questions from these study notes.

NOTES:
{notes}

Return ONLY JSON.

The response must start with [ and end with ].

Use this format:

[
{{
"question":"Question text",
"options":["Option A","Option B","Option C","Option D"],
"answer":"Option A"
}}
]

Rules:

- Exactly 5 questions.
- Exactly 4 options per question.
- The answer MUST exactly match one of the options.
- Questions must be based ONLY on the notes.
- No Markdown.
- No explanation.
- No code fences.
- JSON only.
"""

    ai_response = ask_ai(prompt)

    print("\n==============================")
    print("QUIZ AI RESPONSE:")
    print(ai_response)
    print("==============================\n")

    try:

        cleaned_response = ai_response.strip()

        if cleaned_response.startswith("```"):

            cleaned_response = (
                cleaned_response
                .replace("```json", "")
                .replace("```", "")
                .strip()
            )

        questions = json.loads(cleaned_response)

        if isinstance(questions, list):

            return questions

        return []

    except Exception as e:

        print("QUIZ JSON ERROR:", e)

        return []


# =========================================================
# MULTI-AGENT STUDY WORKFLOW
# =========================================================

def multi_agent_study(notes):

    notes_result = notes_analyzer_agent(notes)

    quiz_result = quiz_agent(notes)

    return {

        "notes": notes_result,

        "quiz": quiz_result

    }


# =========================================================
# COMPLETE MULTI-AGENT SYSTEM
# =========================================================

def multi_agent_system(subjects, hours, days, notes):

    planner_result = study_planner_agent(
        subjects,
        hours,
        days
    )

    study_result = multi_agent_study(notes)

    return {

        "planner": planner_result,

        "notes": study_result["notes"],

        "quiz": study_result["quiz"]

    }


# =========================================================
# HOME PAGE
# =========================================================

@app.route("/")
def home():

    return render_template("index.html")


# =========================================================
# AI STUDY PLANNER
# =========================================================

@app.route("/planner", methods=["GET", "POST"])
def planner():

    result = None

    if request.method == "POST":

        subjects = request.form.get(
            "subjects",
            ""
        )

        hours = request.form.get(
            "hours",
            ""
        )

        days = request.form.get(
            "days",
            ""
        )

        result = study_planner_agent(
            subjects,
            hours,
            days
        )

    return render_template(
        "planner.html",
        result=result
    )


# =========================================================
# NOTES ANALYZER
# =========================================================

@app.route("/analyze-notes", methods=["POST"])
def analyze_notes():

    notes = request.form.get(
        "notes",
        ""
    )

    if not notes.strip():

        return render_template(
            "index.html",
            error="Please enter your notes first."
        )

    notes_result = notes_analyzer_agent(
        notes
    )

    quiz_questions = quiz_agent(
        notes
    )

    return render_template(
        "index.html",
        notes_result=notes_result,
        quiz_questions=quiz_questions,
        original_notes=notes
    )


# =========================================================
# QUIZ AGENT
# =========================================================

@app.route("/generate-quiz", methods=["POST"])
def generate_quiz():

    notes = request.form.get(
        "quiz_notes",
        ""
    )

    if not notes.strip():

        return render_template(
            "index.html",
            error="Please enter some notes first."
        )

    quiz_questions = quiz_agent(
        notes
    )

    return render_template(
        "index.html",
        quiz_questions=quiz_questions,
        quiz_notes=notes
    )


# =========================================================
# MULTI-AGENT DASHBOARD
# =========================================================

@app.route(
    "/dashboard",
    methods=["GET", "POST"]
)
def dashboard():

    result = None

    if request.method == "POST":

        subjects = request.form.get(
            "subjects",
            ""
        )

        hours = request.form.get(
            "hours",
            ""
        )

        days = request.form.get(
            "days",
            ""
        )

        notes = request.form.get(
            "notes",
            ""
        )

        result = multi_agent_system(
            subjects,
            hours,
            days,
            notes
        )

    return render_template(
        "dashboard.html",
        result=result
    )


# =========================================================
# START APPLICATION
# =========================================================

if __name__ == "__main__":

    app.run(debug=True)